services:
  kong:
    image: kong:3.6
    container_name: kong
    ports:
      - "8000:8000"     # Public Gateway (HTTP)
      - "8001:8001"     # Admin API
      - "8443:8443"     # HTTPS 
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
      KONG_LOG_LEVEL: debug
      KONG_ADMIN_LISTEN: 0.0.0.0:8001   # <- Add this line

    volumes:
      - ./kong-volume/kong.yml:/usr/local/kong/kong.yml
      - ./kong-volume/certs:/etc/kong/certs
    networks:
      - vifinancenet

  
  user_service:
      build:
        context: .
        dockerfile: UserService/Dockerfile
      image: dattran453/user_service:v1.0.2
      container_name: user_service
      expose:
        - "6998"
      ports:
        - "6998:6998"
      env_file:
        - .env
      depends_on:
        - db
        - redis
      networks:
        - vifinancenet
    
  authentication_service:
      build:
        context: .
        dockerfile: AuthService/Dockerfile
      image: dattran453/authentication_service:v1.0.2
      container_name: authentication_service
      expose:
        - "6999"
      ports:
        - "6999:6999"
      env_file:
        - .env
      depends_on:
        - db
        - redis
      networks:
        - vifinancenet
  search_service:
    build:
      context: .
      dockerfile: SearchService/Dockerfile-1.0.2
    image: dattran453/search_service:v1.0.2
    container_name: search_service
    expose:
      - "7001"
    ports:
      - "7001:7001"
    env_file:
      - .env
    volumes:
      - hf-models:/app/models/hub
    depends_on:
      - authentication_service
      - db
      - redis 
    networks:
      - vifinancenet

  summariser_service:
    build:
      context: .
      dockerfile: SummariserService/Dockerfile-1.0.2
    image: dattran453/summariser_service:v1.0.2
    container_name: summariser_service
    expose:
      - "7002"
    ports:
      - "7002:7002"
    env_file:
      - .env
    volumes:
      - hf-models:/app/models/hub
    depends_on:
      - search_service
      - authentication_service
      - redis
    networks:
      - vifinancenet

  analysis_service:
    build:
      context: .
      dockerfile: AnalysisService/Dockerfile-1.0.2
    image: dattran453/analysis_service:v1.0.2
    container_name: analysis_service
    expose:
      - "7003"
    ports:
      - "7003:7003"
    env_file:
      - .env
    volumes:
      - hf-models:/app/models/hub
    depends_on:
      - search_service
      - summariser_service
      - authentication_service
      - db
      - redis
    networks:
      - vifinancenet

  logging_service:
    build:
      context: .
      dockerfile: LoggingService/Dockerfile-1.0.2
    image: dattran453/logging_service:v1.0.2
    container_name: logging_service
    expose:
      - "7004"
    ports:
      - "7004:7004"
    env_file:
      - .env
    depends_on:
      - search_service
      - authentication_service
      - summariser_service
      - analysis_service
    networks:
      - vifinancenet

  db:
    image: cockroachdb/cockroach:v23.1.11
    container_name: vifinancenews_db
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    networks:
      - vifinancenet
    env_file:
      - .env
    environment:
      - COCKROACH_DB_PASSWORD=${COCKROACH_DB_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - JDBC_DATABASE_URL=${JDBC_DATABASE_URL}

  redis:
    image: redis
    container_name: vifinannews_redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST_USR_DATA: ${REDIS_HOST_USR_DATA}
      REDIS_PASSWORD_USR_DATA: ${REDIS_PASSWORD_USR_DATA}
    networks:
      - vifinancenet

networks:
  vifinancenet:
    driver: bridge

volumes:
  hf-models:
    external: true      
  cockroach-data:
   


