apiVersion: apps/v1
kind: Deployment
metadata:
  name: vifinancenews-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vifinancenews-db
  template:
    metadata:
      labels:
        app: vifinancenews-db
    spec:
      containers:
        - name: db
          image: cockroachdb/cockroach:v23.1.11
          command: ["start-single-node", "--insecure"]
          ports:
            - containerPort: 26257
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: vifinancenews-config
            - secretRef:
                name: vifinancenews-secret